### PR TITLE
Fix scaling and gravity

### PR DESCRIPTION
**Pull request by stimpfli**
This PR aims at fixing the double scaling 1e6 in the precedent versions. After this PR every object and physical quantities are scaled by 1e3 and are consistent with each other. 
(Before size scaling was 1e6 while gravity scaling was 1e5)
This PR adapts the Tarsus bending even if this could be further improved.

### CODE REVIEW

**Review by sibocw — COMMENTED** [review]
The content looks good to me. Three technical comments:
1. We should merge this into the v1.0.0 branch instead of main because some more changes have been made to the main `nmf_mujoco.py` module. Nothing major, but the default parameters are in different places now. Do you want to make the changes? I can also do it; should take just a few minutes.
2. Does anything in the kinematic replay *script* need to be changed?
3. We should at some point clean up the mjcf files and keep just one that's used. Doesn't have to be now though.

**Comment by sibocw** [comment]
In fact don't worry, I can fix it and merge it into v1.0.0

**Comment by stimpfli** [comment]
> In fact don't worry, I can fix it and merge it into v1.0.0

Thank you !!

**Comment by sibocw** [comment]
OK, this fixes #35 , merging

**Pull request merged**
