### PR TITLE
Path integration: allow different contact force thresholds for different legs, filter contact force signal

### PR DESCRIPTION
**Pull request by sibocw**
### Description
1. Allow different contact force thresholds (used for stance/swing detection) for fore/mid/hind legs.
2. Filter contact force signal — hindleg contact might be noisy
3. ~~Try path integration over complex terrain~~ unrealistic — arena too big and requires very stable physics.

### Types of changes

- [ ] Bugfix
- [x] New feature
- [ ] Refactor / Code style update (no logical changes)
- [ ] Build / CI changes
- [ ] Documentation Update
- [ ] Other (explain)

### Does this address any currently open issues?
[list open issues here]

### CODE REVIEW

**Comment by sibocw** [comment]
(Commits up to here are used for v1_SW of the Figure 4a-c)

**Comment by tkclam** [comment]
I temporarily changed to using joblib to get it to run. Not sure why multiprocessing didn't work

**Comment by sibocw** [comment]
do you want to push your version to dev-v1.0.0?

**Comment by tkclam** [comment]
done

**Pull request merged**
